import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({executablePath:CHROME,headless:false,args:['--window-size=1400,1000'],defaultViewport:{width:1400,height:1000}});
const p=await b.newPage();
p.on('console',m=>{ const t=m.text(); if(t.includes('svgport-mesh')||/error/i.test(m.type())) console.log('  PAGE>',t); });
p.on('pageerror',e=>console.log('  PAGEERROR>',e.message));
await p.goto('http://localhost:5182/desk?test=suzanne',{waitUntil:'networkidle2',timeout:60000});
await p.waitForSelector('canvas',{timeout:30000}); await sleep(8000);
console.log('--- setting svg-port ---');
await p.evaluate(()=>window.__dd_canvas3d.setAiMeshMaterialMode('svg-port'));
await sleep(6000);
console.log('--- done ---');
await b.close();
